/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-n9.1-dev-1828-g6120b70d66"
#endif /* AVUTIL_FFVERSION_H */
