/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-n9.1-dev-1348-gbfac54a03b"
#endif /* AVUTIL_FFVERSION_H */
